


export enum KAFKA_PROJECT_EVENTS {
    CREATED = 'CREATED',
    ACTIVE = 'ACTIVE',
    INACTIVE = 'INACTIVE',
    DELETED = 'DELETED',
    UPDATED = 'UPDATED'
}

export const CACHE_KEY = 'projects';


export enum PROJECT_STATUS {
    PENDING = 'PENDING',
    ACTIVE = 'ACTIVE',
    INACTIVE = 'INACTIVE',
    COMPLETED = 'COMPLETED'
}